# This is a basic workflow to help you get started with Actions

name: Publish

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
     - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  move:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: "startsWith(github.event.head_commit.message, '[task-publish]')"
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Pull repository
        run: git pull
      
      - name: Copy README
        run: cp readme.md ./docs
        
      - name: Commit files
        run: |
          git add .
          git config --local user.email "action@github.com"
          git config --local user.name "[auto] Publish Workflow"
          git commit -m "[task-deploy] Put readme into docs" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
